
  name: twinux
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Fast and native electron based Twitter client # 79 char long summary
  description: |
    Whenever you want to post on Twiter from a Linux machine, 
    it sometimes takes a while to start up the browser, type in twitter.com
    and sign in. Isn't it? Well, not any more! Thanks to twinux, you can now
    just open up the app and away you go!

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
   
    electron-launch:
    plugin: dump
    source: files/
    prepare: |
      chmod +x bin/electron-launch

  apps:
    myApp:
      command: bin/electron-launch $SNAP/usr/lib/myApp/myApp
      desktop: usr/share/applications/myApp.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
      environment:
        TMPDIR: $XDG_RUNTIME_DIR
